fieldLayouts:
  4d1bca6d-66f6-47d1-ae49-cd32793634e2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: topics
name: Topics
siteSettings:
  34463b82-dd3f-441c-b9c6-59c351e847aa:
    hasUrls: true
    template: pages/topic
    uriFormat: 'topics/{slug}'
structure:
  maxLevels: 1
  uid: 2b4d73cc-b09e-4bae-8a4d-5a7b6190a358
