field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Blocks
fieldLayouts:
  740cffdc-873e-42da-ab3b-9f6a01003077:
    tabs:
      -
        elements:
          -
            fieldUid: c4d11cc3-ff49-4b48-ad2a-d5a30294d552 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 479c17fb-3144-43b4-9417-f940264f6a71 # Headline Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b911f8a5-3dbc-4aa9-8be2-9eb2c9c8a2ed # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a1609989-70ec-42e9-a2d0-ce1a902593c7 # Records
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fac14507-5966-4d29-8eeb-fb358414aaaf # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07fd881e-0862-439b-a7f3-7232454c1947 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b947d0e1-da59-4426-bb04-17175245afa2 # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b99b85fc-06c0-4960-bcda-7f07690ef20d # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  07fd881e-0862-439b-a7f3-7232454c1947: # Layout
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: ''
    name: Layout
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  479c17fb-3144-43b4-9417-f940264f6a71: # Headline Style
    contentColumnType: string
    fieldGroup: null
    handle: headlineStyle
    instructions: ''
    name: 'Headline Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a1609989-70ec-42e9-a2d0-ce1a902593c7: # Records
    contentColumnType: string
    fieldGroup: null
    handle: records
    instructions: ''
    name: Records
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # News
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b99b85fc-06c0-4960-bcda-7f07690ef20d: # Background
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: ''
    name: Background
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b911f8a5-3dbc-4aa9-8be2-9eb2c9c8a2ed: # Intro Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: 'Intro Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b947d0e1-da59-4426-bb04-17175245afa2: # Spacing
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: ''
    name: Spacing
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c4d11cc3-ff49-4b48-ad2a-d5a30294d552: # Headline
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fac14507-5966-4d29-8eeb-fb358414aaaf: # Buttons
    contentColumnType: text
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      addRowLabel: 'Add Button'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - url
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: entries
name: Entries
sortOrder: 5
