field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Blocks
fieldLayouts:
  a1f0f4d1-9056-4f56-b262-8722794749a3:
    tabs:
      -
        elements:
          -
            fieldUid: 7506709b-79c3-40ab-b4d3-5ce0fa5ba5bc # Headlin
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 51b4cdd8-a3aa-47f5-bbb3-f01ce199d3d8 # Headline Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c441b407-6c5c-4101-b07b-1883f705c486 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aaa3f092-4a89-4ed0-9389-471df91b59d1 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c864b8d2-2de8-4995-9bb6-4647bee68943 # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8fb8abb9-c8de-487c-ae92-012e8f094ca2 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8fb8abb9-c8de-487c-ae92-012e8f094ca2: # Background
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: ''
    name: Background
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  51b4cdd8-a3aa-47f5-bbb3-f01ce199d3d8: # Headline Style
    contentColumnType: string
    fieldGroup: null
    handle: headlineStyle
    instructions: ''
    name: 'Headline Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  5347a201-6da8-47ff-bc5b-20a0dc63d44e: # Icons
    contentColumnType: text
    fieldGroup: null
    handle: icons
    instructions: ''
    name: Icons
    searchable: true
    settings:
      addRowLabel: 'Add Icon'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Icon URL'
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - url
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Headline
                -
                  - handle
                  - headline
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
          -
            - col5
            -
              __assoc__:
                -
                  - heading
                  - 'Link Label'
                -
                  - handle
                  - linkLabel
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col6
            -
              __assoc__:
                -
                  - heading
                  - 'Link URL'
                -
                  - handle
                  - linkUrl
                -
                  - width
                  - ''
                -
                  - type
                  - url
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  7506709b-79c3-40ab-b4d3-5ce0fa5ba5bc: # Headlin
    contentColumnType: text
    fieldGroup: null
    handle: headlin
    instructions: ''
    name: Headlin
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aaa3f092-4a89-4ed0-9389-471df91b59d1: # Layout
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: ''
    name: Layout
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Horizontal
            -
              - value
              - horizontal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Vertical
            -
              - value
              - vertical
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Vertical Alternating'
            -
              - value
              - verticalAlternating
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c441b407-6c5c-4101-b07b-1883f705c486: # Buttons
    contentColumnType: text
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      addRowLabel: 'Add Button'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - url
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  c864b8d2-2de8-4995-9bb6-4647bee68943: # Spacing
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: ''
    name: Spacing
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: iconList
name: 'Icon List'
sortOrder: 6
