contentColumnType: string(255)
fieldGroup: 1e0f22f0-2c77-45f2-a8dd-9405520e5ce0
handle: emergencyMessageUrl
instructions: ''
name: 'Link URL to "Learn More"'
searchable: false
settings:
  maxLength: '255'
  placeholder: 'https://www.example.com'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
